// ---------------------------------------------------------------------------
// The environment every child process this app spawns should inherit.
//
// The app's OWN network calls were moved onto Chromium's stack, which reads the
// Windows certificate store and therefore copes with antivirus HTTPS scanning.
// The processes it SPAWNS did not get that fix, and they need it just as much:
// Chatterbox's server downloads its model from Hugging Face with Python's
// `requests`, which trusts its own bundled CA list and nothing else.
//
// The symptom is nasty because it does not look like a network problem. The
// server starts, binds its port, answers the health check, reports "running ✓"
// in the UI — and has no model, because the download failed minutes earlier:
//
//     CRITICAL: TTS Model failed to load on startup
//     TTS request failed: Model not loaded.
//
// So the app says the engine is up, and every attempt to speak fails. Passing
// the bundle at spawn time is the difference between that and a working engine.
//
// The bundle is generated by tools/make-ca-bundle.ps1 and is machine-specific,
// so it is absent on machines that don't need it — in which case nothing is
// added and the child sees exactly what it saw before.
// ---------------------------------------------------------------------------

import { app } from "electron";
import { existsSync } from "node:fs";
import path from "node:path";

/** Where the generated bundle lives, packaged or not. */
function caBundlePath(): string | null {
  const candidates = [
    // Running from source (npm run dev) — the repo root is two up from
    // out/main, and app.getAppPath() points at the project.
    path.join(app.getAppPath(), "tools", "windows-ca-bundle.pem"),
    // Packaged: alongside the executable's resources.
    path.join(process.resourcesPath ?? "", "tools", "windows-ca-bundle.pem"),
  ];
  for (const c of candidates) {
    if (c && existsSync(c)) return c;
  }
  return null;
}

/**
 * `process.env` plus the certificate bundle, for handing to spawn().
 *
 * PYTHONUTF8 is here for a second, unrelated reason that cost a full install:
 * Chatterbox's installer prints a "✓", and on a machine whose console codepage
 * is not UTF-8 — cp1253 here, because the OS is Greek — Python dies with
 * UnicodeEncodeError partway through. It exits 0 while doing it, so the failure
 * is invisible unless someone reads the log.
 */
export function childEnv(extra: Record<string, string> = {}): NodeJS.ProcessEnv {
  const ca = caBundlePath();
  return {
    ...process.env,
    PYTHONUTF8: "1",
    PYTHONIOENCODING: "utf-8",
    ...(ca ? { SSL_CERT_FILE: ca, REQUESTS_CA_BUNDLE: ca, CURL_CA_BUNDLE: ca } : null),
    ...extra,
  };
}

/** True when a bundle was found — for telling the user why a download failed. */
export function hasCaBundle(): boolean {
  return caBundlePath() !== null;
}
