import type {
  Fps,
  RenderSettings,
  SpeakerConfig,
  SubtitleConfig,
  TrackWaveform,
} from "./types";

/**
 * A complete saved look: everything that decides how the video *appears*, and
 * nothing that decides what it *says*. Script, narration audio, language and
 * API keys are deliberately excluded, so one preset is reusable across
 * completely different videos.
 *
 * Every field is optional on read, so a preset written by an older build — or
 * by hand, or generated by an AI — still loads, falling back to defaults for
 * anything absent. That tolerance is what makes presets a sane hand-off format.
 */
export interface ProjectPreset {
  render?: RenderSettings;
  fps?: Fps;
  speakers?: SpeakerConfig[];
  musicWaveform?: TrackWaveform;
  musicColor?: string;
  subtitles?: SubtitleConfig;
  /** How background clips are treated — not *which* clips, which belong to the
   *  script rather than to the look. */
  backgroundDim?: number;
  backgroundCrossfadeMs?: number;
  savedAt: number;
  /** Shown in the preset list. Built-ins use it to say what they're for. */
  description?: string;
}

/** Alias kept so older imports keep resolving. */
export type ProjectTemplate = ProjectPreset;
